version: '3.8'
services:
  gateway:
    build: ./gateway
    image:  amazoncorretto
    container_name: "shareit_gateway"
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: amazoncorretto
    container_name: "shareit_server"
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  db:
    image: postgres:14-alpine
    container_name: "data_base"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_user=postgres
      - POSTGRES_PASSWORD=mywords
